title: Michal Spano
description: Software Engineering | Open Source

baseurl: /michalspano.github.io   #name of GitHub repository
# url: michalspano.com            #custom url to be used instead of GitHub repository
email: "mailto:spano@chalmers.se"

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
twitter:  "michalspano"
linkedin: "michalspano"
github:   "michalspano"
flickr:   "197352203@N08"

# Markdown
highlighter: rouge
markdown: kramdown

# Google Analytics
# analytics: ""

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - terminarium.md
      - dotfiles.md
      - openweathermaps.md
      - compsci.md
      - swedish-bot.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
